org: jomunoz075
app: aws-test-project-serverless-cdci
service: aws-rds-proxy-pg
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
