app: aws-rds-proxy-pg
org: jomunoz075
service: aws-rds-proxy-pg
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3
  stackName: service-dev

plugins:
  - serverless-deployment-bucket
functions:
  databasepg:
    handler: handler.databasepg
    events:
      - httpApi:
          path: /databasepg
          method: get
